"""Feature extraction package for deeplogbot."""

from .base import BaseFeatureExtractor
from .schema import LogSchema, get_schema, register_schema, SCHEMA_REGISTRY
from .registry import (
    FeatureRegistry,
    FeatureDefinition,
    FeatureCategory,
    ComputationStage,
    get_feature_documentation,
    print_feature_summary,
    ALL_FEATURES,
    NEW_FEATURES,
    BASIC_FEATURES,
    TEMPORAL_FEATURES,
    YEARLY_FEATURES,
    BEHAVIORAL_FEATURES,
    INTERACTION_FEATURES,
    SIGNATURE_FEATURES,
    TIMING_FEATURES,
    ACCESS_PATTERN_FEATURES,
    USER_DISTRIBUTION_FEATURES,
    STATISTICAL_FEATURES,
    SESSION_FEATURES,
    COMPARATIVE_FEATURES,
    # Time series feature categories
    OUTBURST_FEATURES,
    PERIODICITY_FEATURES,
    TREND_FEATURES,
    RECENCY_FEATURES,
    DISTRIBUTION_FEATURES,
    TIMESERIES_FEATURES,
)
from .providers.ebi import (
    # EBI Schema
    LogEbiSchema,
    EBI_SCHEMA,
    # EBI Extractors
    extract_location_features,
    extract_location_features_ebi,
    YearlyPatternExtractor,
    TimeOfDayExtractor,
    CountryLevelExtractor,
    NewBotDetectionFeaturesExtractor,
    TimeSeriesFeaturesExtractor,
    TimeWindowExtractor,
    # Behavioral
    extract_behavioral_features,
    extract_advanced_behavioral_features,
    add_bot_interaction_features,
    add_bot_signature_features,
    extract_timing_precision_features,
    extract_user_distribution_features,
    extract_session_behavior_features,
    ADVANCED_BEHAVIORAL_FEATURES,
    NEW_BEHAVIORAL_FEATURES,
    # Discriminative
    extract_discriminative_features,
    extract_access_pattern_features,
    extract_statistical_anomaly_features,
    extract_comparative_features,
    DISCRIMINATIVE_FEATURES,
    NEW_DISCRIMINATIVE_FEATURES,
    # Time Series
    extract_outburst_features,
    extract_periodicity_features,
    extract_trend_features,
    extract_recency_features,
    extract_distribution_shape_features,
    extract_all_timeseries_features,
    ALL_TIMESERIES_FEATURES,
)

__all__ = [
    # Base classes
    "BaseFeatureExtractor",
    # Registry
    "FeatureRegistry",
    "FeatureDefinition",
    "FeatureCategory",
    "ComputationStage",
    "get_feature_documentation",
    "print_feature_summary",
    "ALL_FEATURES",
    "NEW_FEATURES",
    # Feature lists by category
    "BASIC_FEATURES",
    "TEMPORAL_FEATURES",
    "YEARLY_FEATURES",
    "BEHAVIORAL_FEATURES",
    "INTERACTION_FEATURES",
    "SIGNATURE_FEATURES",
    "TIMING_FEATURES",
    "ACCESS_PATTERN_FEATURES",
    "USER_DISTRIBUTION_FEATURES",
    "STATISTICAL_FEATURES",
    "SESSION_FEATURES",
    "COMPARATIVE_FEATURES",
    # Time series feature lists
    "OUTBURST_FEATURES",
    "PERIODICITY_FEATURES",
    "TREND_FEATURES",
    "RECENCY_FEATURES",
    "DISTRIBUTION_FEATURES",
    "TIMESERIES_FEATURES",
    # Extractors
    "YearlyPatternExtractor",
    "TimeOfDayExtractor",
    "CountryLevelExtractor",
    "NewBotDetectionFeaturesExtractor",
    "TimeSeriesFeaturesExtractor",
    "TimeWindowExtractor",
    # Extraction functions
    "extract_location_features",
    "extract_location_features_ebi",
    "extract_behavioral_features",
    "extract_advanced_behavioral_features",
    "add_bot_interaction_features",
    "add_bot_signature_features",
    "extract_timing_precision_features",
    "extract_user_distribution_features",
    "extract_session_behavior_features",
    "extract_discriminative_features",
    "extract_access_pattern_features",
    "extract_statistical_anomaly_features",
    "extract_comparative_features",
    # Time series extraction functions
    "extract_outburst_features",
    "extract_periodicity_features",
    "extract_trend_features",
    "extract_recency_features",
    "extract_distribution_shape_features",
    "extract_all_timeseries_features",
    "ALL_TIMESERIES_FEATURES",
    # Feature lists
    "ADVANCED_BEHAVIORAL_FEATURES",
    "NEW_BEHAVIORAL_FEATURES",
    "DISCRIMINATIVE_FEATURES",
    "NEW_DISCRIMINATIVE_FEATURES",
    # Schema
    "LogSchema",
    "LogEbiSchema",
    "EBI_SCHEMA",
    "get_schema",
    "register_schema",
    "SCHEMA_REGISTRY",
]
